# -*- coding: utf-8 -*-
"""solemneanto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12HuPgrO39g7WSER5gGZDcwrLLjuUnv_-

abajo esta el codigo del grafico
"""

st.header("Selecciona columnas para gráficos")
    columnas_numericas = df.select_dtypes(include=['number']).columns.tolist()
    x_axis = st.selectbox('Selecciona la variable para el eje X', columnas_numericas)
    y_axis = st.selectbox('Selecciona la variable para el eje Y', columnas_numericas)

    # Rango personalizado para ejes
    min_x, max_x = st.slider(f"Selecciona el rango para {x_axis}", float(df[x_axis].min()), float(df[x_axis].max()), (float(df[x_axis].min()), float(df[x_axis].max())))
    min_y, max_y = st.slider(f"Selecciona el rango para {y_axis}", float(df[y_axis].min()), float(df[y_axis].max()), (float(df[y_axis].min()), float(df[y_axis].max())))

    # Filtrar DataFrame
    df_filtrado = df[(df[x_axis] >= min_x) & (df[x_axis] <= max_x) & (df[y_axis] >= min_y) & (df[y_axis] <= max_y)]

    # Selección del tipo de gráfico
    tipo_grafico = st.selectbox("Selecciona el tipo de gráfico", ['Dispersión', 'Línea', 'Barra'])

    # Crear gráfico
    plt.figure(figsize=(10, 6))

    if tipo_grafico == 'Dispersión':
        plt.scatter(df_filtrado[x_axis], df_filtrado[y_axis], color='blue')
        plt.title('Gráfico de Dispersión')
    elif tipo_grafico == 'Línea':
        plt.plot(df_filtrado[x_axis], df_filtrado[y_axis], marker='o', color='green')
        plt.title('Gráfico de Línea')
    elif tipo_grafico == 'Barra':
        plt.bar(df_filtrado[x_axis], df_filtrado[y_axis], color='orange')
        plt.title('Gráfico de Barra')